---
title: "Analysis for SN Paper 1 - Inference"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(haven)
library(stargazer)
library(AER)
library(sandwich)
library(lmtest)

# Parameters
data_file <- here::here("data/stu_admin_all_with_netvars.Rds")
trends_file <- here::here("data/trends.csv")
fac_res_file <- here::here("data/fac_res_prop.csv")
n_studymates_file <- here::here("data/n_studymates.csv")
```


Read main data file:


```{r, message=F, warning=F}
df <-
  data_file %>%
  read_rds() %>% 
  filter(stu_merge == 3) %>% 
  mutate_at(vars(contains("ea_seats_reser")), replace_na, replace = 0) %>% 
  left_join(
    read_csv(fac_res_file),
    by = "department_id"
  ) %>% 
  left_join(
    read_csv(n_studymates_file),
    by = "stdid"
  ) %>% 
  mutate(
    female = gender - 1,
    age = 2017 - lubridate::year(b_birthdate),
    reservation = dplyr::recode(reservation, "Non-reservation" = 0L, "Reservation" = 1L, .default = NA_integer_),
    stu_res_official = (ea_seats_reserved_students_obc + ea_seats_reserved_students_sc + ea_seats_reserved_students_st) / 100,
    fac_res_official = (ea_seats_reserved_faculty_obc + ea_seats_reserved_faculty_sc + ea_seats_reserved_faculty_st) / 100,
    z_seg_g1 = if_else(grade == 2, b_seg_studymate, NA_real_),
    z_seg_g2 = if_else(grade == 2, e_seg_studymate, NA_real_),
    z_seg_g3 = if_else(grade == 4, b_seg_studymate, NA_real_),
    z_seg_g4 = if_else(grade == 4, e_seg_studymate, NA_real_),
    z_homophily_g1 = if_else(grade == 2, b_homophily, NA_real_),
    z_homophily_g2 = if_else(grade == 2, e_homophily, NA_real_),
    z_homophily_g3 = if_else(grade == 4, b_homophily, NA_real_),
    z_homophily_g4 = if_else(grade == 4, e_homophily, NA_real_),
    z_reciprocity_g1 = if_else(grade == 2, b_reciprocity, NA_real_),
    z_reciprocity_g2 = if_else(grade == 2, e_reciprocity, NA_real_),
    z_reciprocity_g3 = if_else(grade == 4, b_reciprocity, NA_real_),
    z_reciprocity_g4 = if_else(grade == 4, e_reciprocity, NA_real_),
    z_transitivity_g1 = if_else(grade == 2, b_transitivity, NA_real_),
    z_transitivity_g2 = if_else(grade == 2, e_transitivity, NA_real_),
    z_transitivity_g3 = if_else(grade == 4, b_transitivity, NA_real_),
    z_transitivity_g4 = if_else(grade == 4, e_transitivity, NA_real_),
    z_n_studymates_g1 = if_else(grade == 2, b_n_studymates, NA_real_),
    z_n_studymates_g2 = if_else(grade == 2, e_n_studymates, NA_real_),
    z_n_studymates_g3 = if_else(grade == 4, b_n_studymates, NA_real_),
    z_n_studymates_g4 = if_else(grade == 4, e_n_studymates, NA_real_),
  ) 

df <-
  df %>% 
  left_join(
    df %>% 
      group_by(department_id) %>% 
      summarize(stu_res_actual = mean(reservation, na.rm = TRUE)),
    by = "department_id"
  ) %>% 
  mutate_at(
    vars(starts_with(c("z_seg_g", "z_homophily", "z_reciprocity", "z_transitivity", "z_n_stud", "stu_res_", "fac_res_")), age),
    ~ scale(.) %>% as.vector
  )

df %>% 
  select(starts_with(c("z_seg_g", "z_homophily", "z_reciprocity", "z_transitivity", "z_n_stud", "stu_res_", "fac_res_")), age) %>% 
  summary()


# Preparing classid level data for homophily/reciprocity/transitivity at elite/non-elite colleges
df_e <- df %>% distinct(classid, .keep_all = TRUE) %>% filter(elite == 1)
df_ne <- df %>% distinct(classid, .keep_all = TRUE) %>% filter(elite == 0)
```

Checking IV stage-1 assumption:

```{r}
df %>% 
  lm(stu_res_actual ~  z_seg_g1 + female + age + ses + stu_res_official + reservation + elite, data = .) %>%
  linearHypothesis(c("stu_res_official = 0"), vcov = vcovHC, type = "HC1")

df %>% 
  lm(fac_res_actual ~  z_seg_g1 + female + age + ses + fac_res_official + reservation + elite, data = .) %>%
  linearHypothesis(c("fac_res_official = 0"), vcov = vcovHC, type = "HC1")

df %>% 
  lm(stu_res_actual ~  z_seg_g3 + female + age + ses + stu_res_official + reservation + elite, data = .) %>%
  linearHypothesis(c("stu_res_official = 0"), vcov = vcovHC, type = "HC1")

df %>% 
  lm(fac_res_actual ~  z_seg_g3 + female + age + ses + fac_res_official + reservation + elite, data = .) %>%
  linearHypothesis(c("fac_res_official = 0"), vcov = vcovHC, type = "HC1")
```


## Integration v Policy
### Y1 to Y2

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

lm1_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )

lm2_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1)
  )

lm2_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0)
  )

lm3_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1)
  )

lm3_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0)
  )

lm4_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1)
  )

lm4_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0)
  )

lm5_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1)
  )

lm5_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0)
  )

iv1_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv1_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0)
  )

iv2_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv2_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing1.html",
  #report = "vcp",
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```

### Y3 to Y4

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

lm1_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )

lm2_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1)
  )

lm2_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0)
  )

lm3_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1)
  )

lm3_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0)
  )

lm4_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1)
  )

lm4_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0)
  )

lm5_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1)
  )

lm5_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0)
  )

iv1_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv1_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0)
  )

iv2_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv2_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing1.html",
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```

### Elite (Y1 to Y2)

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm1_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm2_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm2_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm3_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm3_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm4_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm4_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm5_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm5_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

iv1_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

iv1_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

iv2_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

iv2_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation at <i>elite</i> colleges - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  type = "html",
  out = "testing2.html",
  omit.stat = c("all"),
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```

### Elite (Y3 to Y4)

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm1_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm2_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm2_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm3_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm3_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm4_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm4_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm5_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm5_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

iv1_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

iv1_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

iv2_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

iv2_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 1)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )


stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation at <i>elite</i> colleges - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  type = "html",
  out = "testing2.html",
  omit.stat = c("all"),
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```


### Non-elite (Y1 to Y2)

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm1_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm2_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm2_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm3_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm3_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm4_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm4_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm5_r <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm5_nr <- 
  lm(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

iv1_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

iv1_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + stu_res_actual |
      z_seg_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

iv2_r <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

iv2_nr <- 
  ivreg(
    z_seg_g2 ~ z_seg_g1 + female + age + ses + fac_res_actual |
      z_seg_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation at <i>non-elite</i> colleges - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  type = "html",
  out = "testing3.html",
  omit.stat = c("all"),
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```

### Non-elite (Y3 to Y4)

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm1_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm2_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm2_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm3_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm3_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm4_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm4_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

lm5_r <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm5_nr <- 
  lm(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

iv1_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

iv1_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + stu_res_actual |
      z_seg_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )

iv2_r <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

iv2_nr <- 
  ivreg(
    z_seg_g4 ~ z_seg_g3 + female + age + ses + fac_res_actual |
      z_seg_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0, elite == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )


stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation at <i>non-elite</i> colleges - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Segregation - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_seg", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  type = "html",
  out = "testing3.html",
  omit.stat = c("all"),
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)

```


## Number of Studymates v Policy
### Y1 to Y2

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

lm1_nr <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )

lm2_r <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1)
  )

lm2_nr <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0)
  )

lm3_r <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1)
  )

lm3_nr <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0)
  )

lm4_r <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1)
  )

lm4_nr <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0)
  )

lm5_r <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1)
  )

lm5_nr <- 
  lm(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0)
  )

iv1_r <- 
  ivreg(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_actual |
      z_n_studymates_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv1_nr <- 
  ivreg(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + stu_res_actual |
      z_n_studymates_g1 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0)
  )

iv2_r <- 
  ivreg(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + fac_res_actual |
      z_n_studymates_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv2_nr <- 
  ivreg(
    z_n_studymates_g2 ~ z_n_studymates_g1 + female + age + ses + fac_res_actual |
      z_n_studymates_g1 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Number of studymates - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Number of studymates - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_n_stud", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing1.html",
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```


### Y3 to Y4

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

lm1_nr <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )

lm2_r <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 1)
  )

lm2_nr <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df %>% filter(reservation == 0)
  )

lm3_r <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 1)
  )

lm3_nr <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df %>% filter(reservation == 0)
  )

lm4_r <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 1)
  )

lm4_nr <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df %>% filter(reservation == 0)
  )

lm5_r <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 1)
  )

lm5_nr <- 
  lm(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df %>% filter(reservation == 0)
  )

iv1_r <- 
  ivreg(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_actual |
      z_n_studymates_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv1_nr <- 
  ivreg(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + stu_res_actual |
      z_n_studymates_g3 + female + age + ses + stu_res_official, 
    data = df %>% filter(reservation == 0)
  )

iv2_r <- 
  ivreg(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + fac_res_actual |
      z_n_studymates_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 1)
  )

iv2_nr <- 
  ivreg(
    z_n_studymates_g4 ~ z_n_studymates_g3 + female + age + ses + fac_res_actual |
      z_n_studymates_g3 + female + age + ses + fac_res_official, 
    data = df %>% filter(reservation == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Number of studymates - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Number of studymates - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_n_stud", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing2.html",
  notes = c(
    "All OLS models control for <i>proportion of seats officially reserved for students and faculty, student gender, student socioeconomic status,</i> and <i>student age</i>.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty. The model also controls for <i>student gender, student socioeconomic status,</i> and <i>student age</i>."
  )
)
```




## Homophily v Policy

### Y1 to Y2

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_actual |
      z_homophily_g1 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_homophily_g2 ~ z_homophily_g1 + stu_res_actual |
      z_homophily_g1 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_homophily_g2 ~ z_homophily_g1 + fac_res_actual |
      z_homophily_g1 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_homophily_g2 ~ z_homophily_g1 + fac_res_actual |
      z_homophily_g1 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 3,
  model.numbers = F,
  dep.var.caption  = "Homophily - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Homophily - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_homophily", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```

### Y3 to Y4

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_actual |
      z_homophily_g3 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_homophily_g4 ~ z_homophily_g3 + stu_res_actual |
      z_homophily_g3 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_homophily_g4 ~ z_homophily_g3 + fac_res_actual |
      z_homophily_g3 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_homophily_g4 ~ z_homophily_g3 + fac_res_actual |
      z_homophily_g3 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 3,
  model.numbers = F,
  dep.var.caption  = "Homophily - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Homophily - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_homophily", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```


## Reciprocity v Policy

### Y1 to Y2

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_actual |
      z_reciprocity_g1 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_reciprocity_g2 ~ z_reciprocity_g1 + stu_res_actual |
      z_reciprocity_g1 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_reciprocity_g2 ~ z_reciprocity_g1 + fac_res_actual |
      z_reciprocity_g1 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_reciprocity_g2 ~ z_reciprocity_g1 + fac_res_actual |
      z_reciprocity_g1 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Reciprocity - End of year 2 (by college status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Reciprocity - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_reciprocity", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing1.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```

### Y3 to Y4

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_actual |
      z_reciprocity_g3 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_reciprocity_g4 ~ z_reciprocity_g3 + stu_res_actual |
      z_reciprocity_g3 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_reciprocity_g4 ~ z_reciprocity_g3 + fac_res_actual |
      z_reciprocity_g3 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_reciprocity_g4 ~ z_reciprocity_g3 + fac_res_actual |
      z_reciprocity_g3 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  title = "Table 12",
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Reciprocity - End of year 4 (by college status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Reciprocity - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_reciprocity", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing2.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```


## Transitivity v Policy

### Y1 to Y2

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_actual |
      z_transitivity_g1 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_transitivity_g2 ~ z_transitivity_g1 + stu_res_actual |
      z_transitivity_g1 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_transitivity_g2 ~ z_transitivity_g1 + fac_res_actual |
      z_transitivity_g1 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_transitivity_g2 ~ z_transitivity_g1 + fac_res_actual |
      z_transitivity_g1 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  title = "Table 13",
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Transitivity - End of year 2 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Transitivity - Start of year 1", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_transitivity", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing1.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```

### Y3 to Y4

```{r, warning=FALSE, results="hide"}
lm1_r <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official, 
    data = df_e
  )

lm1_nr <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official, 
    data = df_ne
  )

lm2_r <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_e
  )

lm2_nr <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3, 
    data = df_ne
  )

lm3_r <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_e
  )

lm3_nr <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4, 
    data = df_ne
  )

lm4_r <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_e
  )

lm4_nr <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5, 
    data = df_ne
  )

lm5_r <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_e
  )

lm5_nr <- 
  lm(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_official + fac_res_official + ea_polic_integration_students3 + ea_polic_integration_students4 + ea_polic_integration_students5 + ea_polic_integration_students6, 
    data = df_ne
  )

iv1_r <- 
  ivreg(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_actual |
      z_transitivity_g3 + stu_res_official, 
    data = df_e
  )

iv1_nr <- 
  ivreg(
    z_transitivity_g4 ~ z_transitivity_g3 + stu_res_actual |
      z_transitivity_g3 + stu_res_official, 
    data = df_ne
  )

iv2_r <- 
  ivreg(
    z_transitivity_g4 ~ z_transitivity_g3 + fac_res_actual |
      z_transitivity_g3 + fac_res_official, 
    data = df_e
  )

iv2_nr <- 
  ivreg(
    z_transitivity_g4 ~ z_transitivity_g3 + fac_res_actual |
      z_transitivity_g3 + fac_res_official, 
    data = df_ne
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm2_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm3_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm4_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm5_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_r, type = "HC1"))),
    sqrt(diag(vcovHC(iv2_nr, type = "HC1")))
  )

stargazer(
  lm1_r, lm1_nr, lm2_r, lm2_nr, lm3_r, lm3_nr, lm4_r, lm4_nr, lm5_r, lm5_nr, iv1_r, iv1_nr, iv2_r, iv2_nr,
  title = "Table 14",
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Transitivity - End of year 4 (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite", "Elite", "Non-elite"),
  covariate.labels = c("Transitivity - Start of year 3", "Mentoring program", "Diverse hostels", "Diverse course sections", "Integration courses", "Proportion of reservation students", "Proportion of reservation faculty", "Constant"),
  keep = c("z_transitivity", "stu_res_act", "fac_res_act", "ea_", "Constant"),
  omit.stat = c("all"),
  type = "html",
  out = "testing2.html",
  notes = c(
    "All OLS models control for proportion of seats officially reserved for students and faculty.",
    "Instruments for IV models: Proportion of seats officially reserved for students and faculty."
  )
)
```




## Student fixed effects

```{r, results="hide"}
df <-
  df %>%
  mutate(
    diff_homophily = e_homophily - b_homophily,
    diff_reciprocity = e_reciprocity - b_reciprocity,
    diff_transitivity = e_transitivity - b_transitivity,
    diff_seg_studymate = e_seg_studymate - b_seg_studymate,
    diff_n_studymate = e_n_studymates - b_n_studymates,
    diff_ct = e_ct_score_perc - b_ct_score_perc,
    diff_ql = e_ql_score_perc - b_ql_score_perc,
    diff_math = e_math_g3_score_perc - b_math_g1_score_perc,
    diff_physics = e_physics_g3_score_perc - b_physics_g1_score_perc
  ) %>%
  mutate_at(
    vars(starts_with("diff_")),
    ~ scale(.) %>% as.vector
  )

  
lm1_r <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 1)
  )

lm1_nr <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 0)
  )

lm1_r_e <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 1, elite == 1)
  )

lm1_nr_e <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 0, elite == 1)
  )

lm1_r_ne <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 1, elite == 0)
  )

lm1_nr_ne <-
  lm(
    diff_seg_studymate ~ diff_n_studymate + diff_homophily + diff_reciprocity + diff_transitivity, 
    data = df %>% filter(reservation == 0, elite == 0)
  )


rob_se <- 
  list(
    sqrt(diag(vcovHC(lm1_r, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_r_e, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr_e, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_r_ne, type = "HC1"))),
    sqrt(diag(vcovHC(lm1_nr_ne, type = "HC1")))
  )


stargazer(
  lm1_r, lm1_nr, lm1_r_e, lm1_nr_e, lm1_r_ne, lm1_nr_ne,
  title = "Table 15: Gains in segregation controlling for student fixed effects",
  se = rob_se,
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Gains in Segregation",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation elite", "Non-reservation elite", "Reservation non-elite", "Non-reservation non-elite"),
  covariate.labels = c("Gains in studymates", "Gains in class homophily", "Gains in class reciprocity", "Gains in class transitivity", "Constant"),
  keep = c("diff_", "Constant"),
  type = "html",
  out = "testing3.html",
  notes = "All OLS models control for student fixed effects."
)
```


