---
title: "Analysis for SN Paper 1 - Experiment"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.retina = 4)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(haven)
library(stargazer)
library(AER)
library(sandwich)
library(lmtest)
library(estimatr)

# Parameters
stufac_file <- here::here("data", "all_appended.dta")
stu_file <- here::here("data", "stu_admin_all_latest.dta")
newscores_file <- here::here("data/new_scoring/friends/newscores.Rds")
```


## Read in data

```{r}
df_stu <- 
  read_dta(stu_file) %>% 
  mutate(
    reservation = dplyr::recode(reservation, "Non-reservation" = 0L, "Reservation" = 1L, .default = NA_integer_)
  )

df <- 
  read_dta(stufac_file) %>% 
  left_join(
    df_stu %>% 
      select(stdid, classid, reservation, ea_stud_group_criteria),
    by = "stdid"
  ) %>% 
  left_join(read_dta(here::here("/data/res_fac_all.dta")), by = "facid") %>% 
  filter(ea_stud_group_criteria == 2) %>% 
  drop_na(reservation)
```


## Assigning sections
 
```{r, message=F}
sections <-
  df %>%
  group_by(classid, course_name, facid) %>% 
  summarise(
    stu_res_section = mean(reservation, na.rm = TRUE),
    n_stu = n()
  ) %>%
  ungroup() %>% 
  filter(n_stu > 1)

seg_scores <-
  df %>% 
  select(stdid, classid, course_name, facid, everything()) %>% 
  arrange(stdid, classid, course_name, facid) %>% 
  left_join(sections, by = c("classid", "course_name", "facid")) %>% 
  group_by(stdid, reservation) %>% 
  summarize(
    fac_res_prop = sum(reservation_fac * credits, na.rm = TRUE) / sum(credits, na.rm = TRUE),
    stu_res_prop = sum(stu_res_section * credits, na.rm = TRUE) / sum(credits, na.rm = TRUE)
  ) %>%
  ungroup() %>% 
  left_join(read_rds(newscores_file), by = "stdid") %>%
  left_join(df_stu %>% select(stdid, classid, elite, grade), by = "stdid") %>% 
  left_join(read_dta("data/controls.dta"), by = "stdid") %>% 
  mutate(
    # stu_diversity = stu_res_prop * (1 - stu_res_prop),
    # fac_diversity = fac_res_prop * (1 - fac_res_prop)
    stu_diversity = if_else(reservation == 0, stu_res_prop, 1 - stu_res_prop),
    fac_diversity = if_else(reservation == 0, fac_res_prop, 1 - fac_res_prop)
  ) %>% 
  filter(grade == 2) %>% 
  mutate_at(
    vars("e_seg_new", "b_seg_new", "stu_diversity", "fac_diversity"),
    ~ scale(.) %>% as.vector
  )
```


```{r}
# extracting file to compare how lpoly works in stata
# seg_scores %>% write_dta(here::here("data/lpoly.dta"), version = 13)
```

## Randomization checks

```{r}
# df %>% 
#   select(stdid, classid, course_name, facid, everything()) %>% 
#   arrange(stdid, classid, course_name, facid) %>% 
#   left_join(sections, by = c("classid", "course_name", "facid")) %>% 
#   left_join(df_stu %>% select(stdid, grade), by = "stdid") %>% 
#   left_join(read_dta("data/controls.dta"), by = "stdid") %>%
#   left_join(read_rds(newscores_file), by = "stdid") %>%
#   filter(grade == 2) %>% 
#   mutate(
#     section_id = str_c(classid, course_name, facid, sep = "_"),
#     classid_new = str_c(classid, course_name, sep = "_")
#     ) %>% 
#   group_by(section_id, classid_new) %>%
#   summarize(
#     n = n(),
#     stu_res_section = mean(stu_res_section, na.rm = TRUE),
#     female = mean(female, na.rm = TRUE),
#     age = mean(age, na.rm = TRUE),
#     score = mean(score, na.rm = TRUE),
#     father_ed_ind = mean(father_ed_ind, na.rm = TRUE),
#     mother_ed_ind = mean(mother_ed_ind, na.rm = TRUE),
#     school_years_english = mean(school_years_english, na.rm = TRUE),
#     b_seg_new = mean(b_seg_new, na.rm = TRUE)
#   ) %>% 
#   filter(n > 1) %>% 
#   lm_robust(stu_res_section ~ b_seg_new + female + age + score + school_years_english, data = ., fixed_effects = ~ classid_new) %>%
#   summary()


seg_scores %>%
  lm_robust(stu_diversity ~ female + age + score + father_ed_ind + school_years_english, data = ., fixed_effects = ~ classid) %>%
  summary()
```

## Figures for non-linearity

```{r, warning = F, message=F, fig.retina=4}
seg_scores %>% 
  mutate(
    reservation = factor(reservation, labels = c("Non-reservation students", "Reservation students"))
  ) %>%
  ggplot(aes(stu_diversity, e_seg_new)) +
  geom_smooth(method = "loess") +
  facet_wrap(vars(reservation)) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Diversity of classmates",
    y = "Segregation",
    caption = "All values reported in standard deviation units."
  )

seg_scores %>% 
  mutate(
    reservation = factor(reservation, labels = c("Non-reservation students", "Reservation students"))
  ) %>%
  ggplot(aes(fac_diversity, e_seg_new)) +
  geom_smooth(method = "loess") +
  facet_wrap(vars(reservation)) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Diversity of faculty",
    y = "Segregation",
    caption = "All values reported in standard deviation units."
  )
```



## Table 1 (All)

```{r, results = "hide"}
lm1 <-
  seg_scores %>%
  filter(reservation == 1) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + factor(father_ed_ind) + factor(mother_ed_ind) + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(reservation == 0) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + factor(father_ed_ind) + factor(mother_ed_ind) + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(reservation == 1) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + factor(father_ed_ind) + factor(mother_ed_ind) + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(reservation == 0) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + factor(father_ed_ind) + factor(mother_ed_ind) + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 4: Effects of diversity of classmates and faculty on segregation",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("stu_diversity", "fac_diversity", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```


## Table 2 (Elite/Selective)

```{r, results = "hide"}
lm1 <-
  seg_scores %>%
  filter(reservation == 1, elite == 1) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(reservation == 0, elite == 1) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(reservation == 1, elite == 1) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(reservation == 0, elite == 1) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 5: Effects of diversity of classmates and faculty on segregation at selective colleges",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("diversity", "fac_res", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```


## Table 3 (Non-elite/non-selective)

```{r, results = "hide"}
lm1 <-
  seg_scores %>%
  filter(reservation == 1, elite == 0) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm2 <-
  seg_scores %>%
  filter(reservation == 0, elite == 0) %>% 
  lm(e_seg_new ~ b_seg_new + stu_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm3 <-
  seg_scores %>%
  filter(reservation == 1, elite == 0) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

lm4 <-
  seg_scores %>%
  filter(reservation == 0, elite == 0) %>% 
  lm(e_seg_new ~ b_seg_new + fac_diversity + classid + female + age + score + father_ed_ind + mother_ed_ind + school_years_english, data = .)

rob_se <-
  list(
    sqrt(diag(vcovHC(lm1, type = "HC1"))),
    sqrt(diag(vcovHC(lm2, type = "HC1"))),
    sqrt(diag(vcovHC(lm3, type = "HC1"))),
    sqrt(diag(vcovHC(lm4, type = "HC1")))
  )

stargazer(
  lm1, lm2, lm3, lm4,
  se = rob_se,
  title = "Table 6: Effects of diversity of classmates and faculty on segregation at non-selective colleges",
  header = F,
  digits = 2,
  model.numbers = F,
  dep.var.caption  = "Segregation (by student reservation status)",
  dep.var.labels.include  = F,
  column.labels   = c("Reservation", "Non-reservation", "Reservation", "Non-reservation"),
  covariate.labels = c("Diversity of classmates", "Diversity of faculty", "Constant"),
  keep = c("diversity", "fac_res", "Constant"),
  keep.stat = c("n"),
  type = "html",
  out = "testing.html",
  notes = c(
    "All models control for pre-treatment student characteristics and department-year fixed effects."
  )
)
```

## Mechanisms

```{r, message = F, warning = F, fig.retina=4}
read_rds(here::here("data/stu_admin_all_with_netvars.Rds")) %>% 
  select(stdid, contains("reciprocity"), contains("transitivity"), contains("homophily")) %>% 
  mutate(
    diff_reciprocity = e_reciprocity - b_reciprocity,
    diff_transitivity = e_transitivity - b_transitivity
  ) %>%
  inner_join(seg_scores, by = "stdid") %>% 
  mutate(
    reservation = factor(reservation, labels = c("Non-reservation", "Reservation"))
  ) %>%
  ggplot(aes(stu_diversity, diff_reciprocity)) +
  geom_smooth(method = "loess", span = 0.8) +
  geom_smooth(method = "lm", linetype = "dashed", color = "red", se = F) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Diversity of classmates",
    y = "Change in reciprocity",
    caption = "All values reported in standard deviation units."
  )

read_rds(here::here("data/stu_admin_all_with_netvars.Rds")) %>% 
  select(stdid, contains("reciprocity"), contains("transitivity"), contains("homophily")) %>% 
  mutate(
    diff_reciprocity = e_reciprocity - b_reciprocity,
    diff_transitivity = e_transitivity - b_transitivity
  ) %>%
  inner_join(seg_scores, by = "stdid") %>% 
  mutate(
    reservation = factor(reservation, labels = c("Non-reservation", "Reservation"))
  ) %>%
  ggplot(aes(stu_diversity, diff_transitivity)) +
  geom_smooth(method = "loess", span = 0.9) +
  geom_smooth(method = "lm", linetype = "dashed", color = "red", se = F) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Diversity of classmates",
    y = "Change in transitivity",
    caption = "All values reported in standard deviation units."
  )
```

