---
title: "Analysis for SN Paper 1 - STERGMs"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(igraph)
library(ggraph)
library(tidygraph)
library(haven)
library(stargazer)
library(statnet)
library(intergraph)
library(metafor)

# Parameters
baseline_network_file <- here::here("data/baseline_network.dta")
endline_network_file <- here::here("data/endline_network.dta")
stu_admin_all_file <- here::here("data/stu_admin_all_latest.dta")

#===============================================================================
```

```{r}
# adding controls
# read_dta(endline_network_file) %>% 
#   left_join(
#     read_dta("data/controls.dta"),
#     by = c("e_node1" = "stdid")
#   ) %>% 
#   write_dta("data/endline_network.dta")
```


## Creating networks for each classroom

```{r}
classids <- read_dta(endline_network_file) %>% select(classid) %>% arrange(classid) %>% distinct() %>% unlist()

b_netlist <- list()
e_netlist <- list()

for (class in classids) {
  print(str_c("Now at class: ", class))
  
  b_nodes <-
    read_dta(baseline_network_file) %>%
    filter(classid == class) %>%
    select(-b_node2) %>%
    mutate(
      reservation = recode(reservation, `Non-reservation` = "0", `Reservation` = "1", .default = NA_character_) %>% as.integer()
    ) %>% 
    distinct()

  b_edges <-
    read_dta(baseline_network_file) %>%
    filter(classid == class) %>%
    select(b_node1, b_node2) %>%
    filter(b_node2 != "")

  e_nodes <-
    read_dta(endline_network_file) %>%
    filter(classid == class) %>%
    select(-e_node2) %>%
    mutate(
      reservation = recode(reservation, `Non-reservation` = "0", `Reservation` = "1", .default = NA_character_) %>% as.integer()
    ) %>%
    distinct()

  e_edges <-
    read_dta(endline_network_file) %>%
    filter(classid == class) %>%
    select(e_node1, e_node2) %>%
    filter(e_node2 != "")
  
  b_netlist[[class]] <-
    graph_from_data_frame(b_edges, b_nodes, directed = TRUE) %>%
    asNetwork()
  
  e_netlist[[class]] <-
    graph_from_data_frame(e_edges, e_nodes, directed = TRUE) %>%
    asNetwork()
}
```

## Running STERGMs

```{r}
results <- tibble()
classids <- c("IR007EE3", "IR008CS1", "IR008CS3", "IR008EE1", "IR008EE3", "IR010CS1") 

for (class in classids) {
  tryCatch(
    {
      print(str_c("Now at class: ", class))
      
      model <- 
        stergm(
          list(b_netlist[[class]], e_netlist[[class]]),
          formation = 
            ~ edges + nodefactor("reservation") + nodematch("reservation", diff = TRUE) + mutual + cyclicalties  + transitiveties,
          dissolution = 
            ~ edges + nodefactor("reservation") + nodematch("reservation", diff = TRUE) + mutual + cyclicalties  + transitiveties,
          estimate = "CMLE",
          times = 1:2,
          control = control.stergm(seed = 100)
        )
      
      summary <- model %>% summary()
      
      results <-
        bind_rows(
          results,
          bind_cols(
            rep(
              class, nrow(summary[["formation"]][["coefs"]][["Estimate"]] %>% as_tibble())
            ) %>% 
              as_tibble() %>% 
              select(classid = value),
            model[["formation.fit"]][["coef"]] %>% names() %>% as_tibble() %>% select(name = value),
            summary[["formation"]][["coefs"]][["Estimate"]] %>% as_tibble() %>% select(form_coef = value),
            summary[["formation"]][["coefs"]][["Std. Error"]] %>% as_tibble() %>% select(form_se = value), 
            summary[["dissolution"]][["coefs"]][["Estimate"]] %>% as_tibble() %>% select(diss_coef = value),
            summary[["dissolution"]][["coefs"]][["Std. Error"]] %>% as_tibble() %>% select(diss_se = value)
          )
        )
    }, 
    error = function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

#results %>% write_csv("data/stergm_results_v1.csv")
```

Meta-analysis:

```{r}
df <- read_csv("data/stergm_results_v1.csv")

df %>%
  mutate(form_var = form_se * form_se) %>% 
  filter(name == "nodefactor.reservation.1") %>% 
  filter(is.finite(form_coef), is.finite(form_var)) %>% 
  rma(form_coef, form_var, data = ., method = "REML")

df %>%
  filter(name == "nodematch.reservation.0") %>% 
  mutate(form_var = form_se * form_se) %>% 
  filter(is.finite(form_coef), is.finite(form_var)) %>% 
  rma(form_coef, form_var, data = ., method = "REML")

df %>%
  filter(name == "nodematch.reservation.1") %>% 
  mutate(form_var = form_se * form_se) %>% 
  filter(is.finite(form_coef), is.finite(form_var)) %>% 
  rma(form_coef, form_var, data = ., method = "REML", slab = classid)
  
```

